pipeline {
    agent none 
    stages {
        stage('Build Code') { 
            steps {
                echo "Build code steps here."
            }
        }
//New comment
        stage('CI Basics') { 
            parallel {
                stage('Unit Tests') { 
                    steps {
                        echo "Unit test execution steps here."
                    }
                }
                stage('Code Quality Check') { 
                    steps {
                        echo "Code quality check execution steps here."
                    }
                }
            }
        }
        stage('Build Image') { 
            steps {
                echo "Build image execution steps here."
            }
        }
        stage('Tag Image') { 
            steps {
                echo "Tag image execution steps here."
            }
        }
        stage('Image Security Scan') { 
            steps {
                echo "Image security scan execution steps here."
            }
        }
        stage('Push Image to Repository') { 
            steps {
                echo "Push image to artifact repository execution steps here."
            }
        }
        stage('Build Ephemeral Env') { 
            steps {
                echo "Build ephemeral environment execution steps here."
            }
        }
        stage('App Deploy to Ephemeral Env') { 
            steps {
                echo "Application deployment to the ephemeral environment execution steps here."
            }
        }
        stage('App Integration Tests') { 
            steps {
                echo "Application integration tests execution steps here."
            }
        }
        stage('Destroy Ephemeral Env') { 
            steps {
                echo "Destroy ephemeral environment execution steps here."
            }
        }
    }
}
